### ISSUE TITLE
최신 버전 표기 오류

### ISSUE THREAD

**Issue by Twibap** [bootpay/client_android_java#3]
부트페이 개발자 문서에 버전 표기가 잘못되어있습니다.
```
dependencies {
    // ...
    implementation 'com.github.bootpay:client_android_java:2.0.123' // 123 -> 122
}
```

[jitpack.io](https://jitpack.io/com/github/bootpay/client_android_java/) 저장소에 버전이 2.0.122 까지만 있더군요.
중간에 2.5.0 버전도 있는데 이것이 최신 버전인가요?

**Comment by ehowlsla** [comment]
중간에 2.5.0은 잘못 표기된 부분입니다. 현재날짜 기준 2.0.127 입니다~
